version: "3"
services:
  mkv-to-mp4-watcher:
    image: marclundgren/node-mkv-to-mp4-watcher:latest
    volumes:
      - ../mkvtest:/watch
    environment:
      - uid=(`id -u marc.lundgren`)
      - gid=(`id -g marc.lundgren`)
